'use client';

import { motion } from 'framer-motion';
import { useDexScreener } from '@/hooks/useDexScreener';
import { useSolanaSupply } from '@/hooks/useSolanaSupply';
import { formatPrice, formatUsd, formatPriceChange } from '@/lib/dexscreener';
import BurnBar from './BurnBar';
import { SITE_CONFIG } from '@/config/constants';

interface StatCardProps {
  label: string;
  value: string;
  sub?: string;
  loading?: boolean;
  subColor?: string;
}

function StatCard({ label, value, sub, loading, subColor = 'text-neutral-500' }: StatCardProps) {
  return (
    <div className="border border-neutral-800/60 rounded-lg p-4 bg-void-soft hover:border-purple-900/50 transition-colors">
      <div className="font-mono text-xs text-neutral-600 uppercase tracking-widest mb-2">{label}</div>
      {loading ? (
        <div className="h-6 w-24 bg-neutral-900 rounded animate-pulse" />
      ) : (
        <>
          <div className="font-mono text-lg font-semibold text-neutral-100">{value}</div>
          {sub && <div className={`font-mono text-xs mt-1 ${subColor}`}>{sub}</div>}
        </>
      )}
    </div>
  );
}

export default function Tokenomics() {
  const { data, loading } = useDexScreener();
  const { supply, loading: supplyLoading, error: supplyError } = useSolanaSupply();

  const priceChange = data?.priceChange24h ?? 0;
  const changeColor = priceChange >= 0 ? 'text-emerald-400' : 'text-red-400';

  return (
    <section id="tokenomics" className="relative py-24 md:py-32 bg-void-soft">
      <div className="absolute inset-0 bg-grid opacity-20 pointer-events-none" />

      <div className="relative z-10 max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">

        {/* Header */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.6 }}
          className="mb-12"
        >
          <div className="font-mono text-xs text-purple-700 tracking-widest mb-3 uppercase">
            {'>'} chain data
          </div>
          <h2 className="font-mono text-3xl sm:text-4xl md:text-5xl font-bold text-purple-400 glow-purple">
            Tokenomics
          </h2>
          <div className="mt-3 section-divider" />
        </motion.div>

        {/* Live stats grid */}
        <motion.div
          initial={{ opacity: 0, y: 16 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.5, delay: 0.1 }}
          className="grid grid-cols-2 md:grid-cols-3 gap-4 mb-10"
        >
          <StatCard
            label="Price"
            value={data ? formatPrice(data.priceUsd) : '—'}
            sub={data ? formatPriceChange(priceChange) + ' 24h' : undefined}
            loading={loading}
            subColor={changeColor}
          />
          <StatCard
            label="Market Cap"
            value={data ? formatUsd(data.marketCap) : '—'}
            loading={loading}
          />
          <StatCard
            label="Liquidity"
            value={data ? formatUsd(data.liquidity) : '—'}
            loading={loading}
          />
          <StatCard
            label="Volume 24H"
            value={data ? formatUsd(data.volume24h) : '—'}
            loading={loading}
          />
          <StatCard
            label="Initial Supply"
            value="1,000,000,000"
          />
          <StatCard
            label="Chain"
            value="Solana"
            sub="SPL Token"
          />
        </motion.div>

        {/* Burn section */}
        <motion.div
          initial={{ opacity: 0, y: 16 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.5, delay: 0.2 }}
          className="border border-purple-900/30 rounded-lg p-6 bg-void-mid/40 glow-box-purple mb-10"
        >
          <div className="flex items-center gap-2 mb-5">
            <span className="text-amber-400 text-lg">🔥</span>
            <h3 className="font-mono text-sm font-semibold text-neutral-200 uppercase tracking-wider">
              Burn Mechanism
            </h3>
          </div>

          <BurnBar
            currentSupply={supply}
            loading={supplyLoading}
            error={supplyError}
          />

          <p className="mt-5 font-sans text-sm text-neutral-500 leading-relaxed">
            Trading fees generated by the $OCTOPUS contract are used to buy back and permanently
            burn tokens, reducing the circulating supply over time. The more the token is traded,
            the more supply is removed — deflationary by design.
          </p>
        </motion.div>

        {/* Static token details */}
        <motion.div
          initial={{ opacity: 0, y: 16 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.5, delay: 0.3 }}
          className="font-mono text-xs text-neutral-600 border border-neutral-900 rounded p-4 space-y-1.5"
        >
          <div className="flex gap-4">
            <span className="text-neutral-700 w-32 shrink-0">Contract</span>
            <span className="text-neutral-500 break-all">{SITE_CONFIG.contractAddress}</span>
          </div>
          <div className="flex gap-4">
            <span className="text-neutral-700 w-32 shrink-0">Network</span>
            <span className="text-neutral-500">Solana Mainnet</span>
          </div>
          <div className="flex gap-4">
            <span className="text-neutral-700 w-32 shrink-0">Decimals</span>
            <span className="text-neutral-500">6</span>
          </div>
          <div className="flex gap-4">
            <span className="text-neutral-700 w-32 shrink-0">Mint Auth</span>
            <span className="text-neutral-500">Revoked</span>
          </div>
          <div className="flex gap-4">
            <span className="text-neutral-700 w-32 shrink-0">Freeze Auth</span>
            <span className="text-neutral-500">Revoked</span>
          </div>
        </motion.div>
      </div>
    </section>
  );
}
